import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../components/navbar/Navbar'
import Provider from "./context/client-provider"
import { getServerSession } from "next-auth/next"
import { authOptions } from "./api/auth/[...nextauth]/route"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)
  return (

    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
          <Navbar navFor="tasks" />
          {children}
        </Provider>
      </body>
    </html>
  )
}
